version: '3.3'
services:
  komga:
    image: gotson/komga
    container_name: komga
    volumes:
      - type: bind
        source: /path/to/config
        target: /config
      - type: bind
        source: /path/to/data
        target: /data
        read_only: true
    ports:
      - 8080:8080
    user: "1000:1000"
    restart: unless-stopped
